Repository radical-group/radical-group.github.io, pull requests merged in 2018-12, with the labels that each got.

#65 scale paper
  _publications/dakka2018scale.md
Labels: content

#63 CSS validation
  _includes/navbar.html
  _layouts/default.html
  css/zoom.css
  style.scss
Labels: bug

#59 Templates for projects list and landing page
  _layouts/default.html
  _layouts/projects.html
  _projects/aimes.md
  _projects/ccc.md
  _projects/extasy.md
  _projects/htbac.md
  _projects/iceberg.md
  _projects/midas.md
  _projects/molssi.md
  _projects/polar-computing.md
  _projects/power_of_many.md
  _projects/rct.md
  _projects/scalems.md
  images/projects/FFP_New.png
  images/projects/aimes_logo.png
  images/projects/ccc.jpg
  images/projects/ccc_logo.jpg
  images/projects/extasy.png
  images/projects/extasy_logo.png
  images/projects/htbac.png
  images/projects/htbac_logo.jpg
  images/projects/iceberg_logo.png
  images/projects/mgray_800x600.png
  images/projects/midas.png
  images/projects/midas_logo.png
  images/projects/molssi_logo.png
  images/projects/molssi_logo_big.png
  images/projects/molssi_main_logo.png
  images/projects/pom.png
  images/projects/pom_logo.jpg
  images/projects/prcn.jpg
  images/projects/prcn_logo.jpg
  images/projects/rct_logo.png
  images/projects/rct_transparent.png
  index.html
  projects.md
  style.scss
Labels: bug, content, enhancement, style

#68 update synapse 2018, add rp 2018
  _publications/merzky2018jssp.md
  _publications/merzky2018synapse.md
Labels: content

#57 Iterate on projects intro
  about.md
  projects.md
Labels: content

#67 Iterate publications and fix html errors
  _publications/fisher2012saga.md
  _publications/fox2015implications.md
  _publications/fox2015scalable.md
  _publications/fox2015workshop.md
  _publications/jha2006requirements.md
  _publications/jha2015high.md
  _publications/jha2015towards.md
  _publications/katz2011survey.md
  _publications/luckow2015pilot.md
  _publications/luckow2018pilotstreaming.md
  _publications/merzky2008saga.md
  _publications/turilli2017building.md
  publications.md
  style.scss
Labels: bug, enhancement

#71 Corrected projects template. Issue #69
  _layouts/projects.html
  _projects/midas.md
  _projects/polar-computing.md
Labels: bug

#66 Iteration people list and landing pages
  _layouts/profile.html
  _people/andre_luckow.md
  _people/andre_merzky.md
  _people/aymen-alsaadi.md
  _people/georgios_chantz.md
  _people/hyungro_lee.md
  _people/ioannis_par.md
  _people/jumana_dakka.md
  _people/matteo_turilli.md
  _people/shantenu_jha.md
  _people/vivek_bala.md
  _people/willcheng.md
  images/people/andre_luckow.jpg
  images/people/aymen.jpg
  images/people/willcheng.png
  people.md
Labels: bug, content, enhancement

#76 Fix html/css errors
  _includes/navbar.html
  people.md
  style.scss
Labels: bug

#75 Cleanup headers and scripts
  _config.yml
  _layouts/default.html
  _layouts/profile.html
  style.scss
Labels: enhancement

#78 Adding an extra link to Shantenu's page
  _people/shantenu_jha.md
Labels: enhancement

#81 Grid formatting of people page
  people.md
  style.scss
Labels: enhancement

#82 Giannis' projects and a small bug fix. Work for #80
  _projects/cybermanufacturing.md
  _projects/ffp.md
  images/projects/ffp.png
  images/projects/ffp_logo.png
  projects.md
Labels: enhancement

#83 fixes mobile navbar
  _includes/navbar.html
Labels: bug

#86 Adds Sea Level Rise project
  _projects/sea_ice_level.md
  images/projects/sea_level_rise.jpg
  images/projects/sea_level_rise_logo.jpg
  images/projects/sea_level_rise_original.png
Labels: content

#85 Adds BigPanDA project
  _projects/bigpanda.md
  images/projects/bigpanda.jpg
  images/projects/bigpanda_logo.jpg
  images/projects/bigpanda_logo_original.jpg
  images/projects/bigpanda_original.jpg
  projects.md
  style.scss
Labels: content

#88 Prepares people page for linking to ICEBERG
  _layouts/profile.html
  _people/andre_luckow.md
  _people/andre_merzky.md
  _people/aymen-alsaadi.md
  _people/georgios_chantz.md
  _people/hyungro_lee.md
  _people/ioannis_par.md
  _people/jumana_dakka.md
  _people/matteo_turilli.md
  _people/shantenu_jha.md
  _people/vivek_bala.md
  _people/willcheng.md
  _publications/dakka2018concurrent.md
  _publications/luckow2016hadoop.md
  _publications/turilli2017comprehensive.md
  people.md
  style.scss
Labels: bug, enhancement

#94 Home page redesign
  _config.yml
  _includes/navbar.html
  index.html
  style.scss
Labels: content, enhancement
