Repository radical-group/radical-group.github.io, pull requests merged in 2018-11, with the labels that each got.

#23 Creating project tags
  README.md
  _projects/extasy.md
  _projects/htbac.md
  _projects/iceberg.md
  _projects/midas.md
  _projects/power_of_many.md
  _projects/rp.md
  projects.md
Labels: enhancement

#29 SCALE-MS abstract and landing page
  _projects/scalems.md
Labels: content

#38 Reduce ICEBERG landing page to a single paragraph
  _projects/iceberg.md
Labels: content

#39 Iterate CCC description
  _projects/ccc.md
Labels: content

#40 Iterate ExTASY description
  _projects/extasy.md
Labels: content

#31 Publication building blocks
  _publications/turilli2018building.md
Labels: content

#35 Reduced HTBAC txt to single paragraph
  _projects/htbac.md
Labels: content

#53 Fixing liquid error
  people.md
  publications.md
Labels: bug

#55 updated publications
  _publications/dakka2017concurrent.md
  _publications/dakka2017htbac.md
  _publications/dakka2017learning.md
  _publications/dakka2018concurrent.md
Labels: content

#56 Fix MathJax CDN
  _layouts/default.html
Labels: bug

#60 Remove double underline from mouseover/focus on links
  style.scss
Labels: bug

#64 CI with Travis
  .gitignore
  .travis.yml
  Gemfile
  _config.yml
  script/cibuild
Labels: enhancement
